apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: team-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: 100xdevs/backend-pg:2
          ports:
            - containerPort: 3000
