apiVersion: v1
kind: Service
metadata:
  name: custom-service
  namespace: team-backend
spec:
  selector:
    app: backend-app
  ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
  type: ClusterIP
