apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-template
  template:
    metadata:
      labels:
        app: nginx-template
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
